hymenoptera:
  module: my_predict.inference
  class: Predictor
  Predictor:
    model_config:
      module: model.se_resnet
      class: Resnet
      Resnet:
        layers: ['3', '4', '6', '3']
        image_channels: 3
        num_classes: 2
    weight_path: '''weights/best_model_accuracy=1.0.pth'''
    image_size: '(224, 224)'
    mean: '(0.485, 0.456, 0.406)'
    std: '(0.229, 0.224, 0.225)'
    batch_size: 1
    device: '''cuda'''
    classes:
      0: ant
      1: bee
    
