cifar10:
  module: my_predict.inference
  class: Predictor
  Predictor:
    model_config:
      module: model.model
      class: MobileNetV2
      MobileNetV2:
        pretrained: True
        num_classes: 10
        features_fixed: True
    weight_path: '''weights/cifar10.pth'''
    image_size: '(224, 224)'
    mean: '(0.485, 0.456, 0.406)'
    std: '(0.229, 0.224, 0.225)'
    batch_size: 1
    device: '''cuda'''
    classes:
      0: airplane
      1: automobile
      2: bird
      3: cat
      4: deer
      5: dog
      6: frog
      7: horse
      8: ship
      9: truck
    
