cifar10:
  module: my_predict.inference
  class: Predictor
  Predictor:
    model_config:
      module: model.mobilenet_v2 
      class: MobileNetV2
      MobileNetV2:
        num_classes: 10
    weight_path: '''weights/best_model_accuracy=0.9552149681528662.pth'''
    image_size: '(224, 224)'
    mean: '(0.4914, 0.4822, 0.4465)'
    std: '(0.247, 0.243, 0.261)'
    batch_size: 1
    device: '''cuda'''
    classes:
      0: airplane
      1: automobile
      2: bird
      3: cat
      4: deer
      5: dog
      6: frog
      7: horse
      8: ship
      9: truck
    
