train_dataset:
  module: torchvision.datasets
  class: CIFAR10
  CIFAR10:
    root: '''load_dataset''
    train: True
    download: True
    transform: 
      - 'torchvision.transforms.ToTensor()'
      - 'torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
      - 'torchvision.transforms.Resize(size=224)'

train_loader:
  module: torch.utils.data
  class: DataLoader
  DataLoader:
    shuffle: True
    batch_size: 64

valid_dataset:
  module: torchvision.datasets
  class: CIFAR10
  CIFAR10:
    root: '''load_dataset'''
    train: False
    download: True
    transform:
      - 'torchvision.transforms.ToTensor()'
      - 'torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])'
      - 'torchvision.transforms.Resize(size=224)'

valid_loader:
  module: torch.utils.data
  class: DataLoader
  DataLoader:
    shuffle: False
    batch_size: 64

visualize:
  module: dataset.visualize_dataset
  class: visualize