train_dataset:
  module: dataset.dataset
  class: Dataset
  Dataset:
    dirname: '''dataset/hymenoptera_data/train/'''
    pattern: '''**/*.*'''
    classes:
      ant: 0
      bee: 1
    image_size: '(224, 224)'
    mean: ['0.485', '0.456', '0.406']
    std: ['0.229', '0.224', '0.225']
    transforms:
      - 'torchvision.transforms.RandomVerticalFlip(p=0.5)'
      - 'torchvision.transforms.RandomGrayscale(p=0.5)'
      - 'torchvision.transforms.Resize(size=224)'

train_loader:
  module: torch.utils.data
  class: DataLoader
  DataLoader:
    shuffle: True
    batch_size: 64

valid_dataset:
  module: dataset.dataset
  class: Dataset
  Dataset:
    dirname: '''dataset/hymenoptera_data/val/'''
    pattern: '''**/*.*'''
    classes:
      ant: 0
      bee: 1
    image_size: '(224, 224)'
    mean: ['0.485', '0.456', '0.406']
    std: ['0.229', '0.224', '0.225']

valid_loader:
  module: torch.utils.data
  class: DataLoader
  DataLoader:
    shuffle: False
    batch_size: 64

model:
  module: model.se_resnet 
  class: Resnet
  Resnet:
    layers: [3, 4, 6, 3]
    image_channels: 3
    num_classes: 2

optimizer:
  module: torch.optim
  class: SGD
  SGD:
    lr: 0.01
    momentum: 0.9

lr_scheduler:
  module: torch.optim.lr_scheduler
  class: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.1
    patience: 5
    verbose: True

criterion:
  module: torch.nn
  class: CrossEntropyLoss

early_stopping:
  module: early_stopping.early_stopping
  class: EarlyStopping
  EarlyStopping:
    mode: '''min'''
    patience: 10
    verbose: False
    delta: 0
    path: '''weights/cifar10.pth'''

trainer:
  module: engine.engine
  class: TrainEpoch

validation:
  module: engine.engine
  class: EvalEpoch