train_dataset:
  module: torchvision.datasets
  class: CIFAR10
  CIFAR10:
    root: '''dataset'''
    train: True
    download: True

train_loader:
  module: torch.utils.data
  class: DataLoader
  DataLoader:
    shuffle: True
    batch_size: 64

valid_dataset:
  module: torchvision.datasets
  class: CIFAR10
  CIFAR10:
    root: '''dataset'''
    train: False
    download: True

valid_loader:
  module: torch.utils.data
  class: DataLoader
  DataLoader:
    shuffle: False
    batch_size: 64

model:
  module: model.cifar10 
  class: CIFAR10
  CIFAR10:
    in_channels: 3
    num_classes: 10

optimizer:
  module: torch.optim
  class: SGD
  SGD:
    lr: 0.01
    momentum: 0.9

lr_scheduler:
  module: torch.optim.lr_scheduler
  class: ReduceLROnPlateau
  ReduceLROnPlateau:
    factor: 0.1
    patience: 5
    verbose: True

criterion:
  module: torch.nn
  class: CrossEntropyLoss

trainer:
  module: engine.engine
  class: TrainEpoch

validation:
  module: engine.engine
  class: EvalEpoch